"""initial

Revision ID: 0761753836ed
Revises: 
Create Date: 2026-05-25 14:51:04.647506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0761753836ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('academy_id', sa.Uuid(), nullable=False),
    sa.Column('home_team', sa.String(length=200), nullable=False),
    sa.Column('away_team', sa.String(length=200), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('academy_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('preferred_foot', sa.String(length=10), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('development_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('physical_score', sa.Float(), nullable=True),
    sa.Column('tactical_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('weak_foot_progress', sa.Float(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('minutes_played', sa.Float(), nullable=True),
    sa.Column('top_speed_ms', sa.Float(), nullable=True),
    sa.Column('avg_speed_ms', sa.Float(), nullable=True),
    sa.Column('distance_covered_m', sa.Float(), nullable=True),
    sa.Column('hi_run_count', sa.Integer(), nullable=True),
    sa.Column('sprint_count', sa.Integer(), nullable=True),
    sa.Column('acceleration_profile', sa.JSON(), nullable=True),
    sa.Column('fatigue_index', sa.Float(), nullable=True),
    sa.Column('press_count', sa.Integer(), nullable=True),
    sa.Column('press_success_rate', sa.Float(), nullable=True),
    sa.Column('press_trigger_accuracy', sa.Float(), nullable=True),
    sa.Column('recovery_shadow_score', sa.Float(), nullable=True),
    sa.Column('ppda_contribution', sa.Float(), nullable=True),
    sa.Column('pitch_control_contribution', sa.Float(), nullable=True),
    sa.Column('dangerous_zone_occupancy', sa.Float(), nullable=True),
    sa.Column('heatmap_data', sa.JSON(), nullable=True),
    sa.Column('space_creation_index', sa.Float(), nullable=True),
    sa.Column('run_threat_score', sa.Float(), nullable=True),
    sa.Column('shadow_escape_rate', sa.Float(), nullable=True),
    sa.Column('third_man_availability', sa.Float(), nullable=True),
    sa.Column('decision_score', sa.Float(), nullable=True),
    sa.Column('xt_added', sa.Float(), nullable=True),
    sa.Column('under_pressure_pass_quality', sa.Float(), nullable=True),
    sa.Column('turnover_location_value', sa.Float(), nullable=True),
    sa.Column('weak_foot_action_pct', sa.Float(), nullable=True),
    sa.Column('weak_foot_success_rate', sa.Float(), nullable=True),
    sa.Column('duel_typology', sa.JSON(), nullable=True),
    sa.Column('positional_iq_score', sa.Float(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_match_stats')
    op.drop_table('development_scores')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('academies')
    # ### end Alembic commands ###
