"""add_password_hash_to_academy

Revision ID: 888652ddf0d9
Revises: 0761753836ed
Create Date: 2026-05-25 15:10:07.044334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888652ddf0d9'
down_revision: Union[str, Sequence[str], None] = '0761753836ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academies', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
